name: Heroku Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bdb-2021"
          heroku_email: "mrkaye97@gmail.com"
          justlogin: true      
      - name: Deploy
        env:
          ENVIRONMENT: ${{secrets.ENVIRONMENT}}
          ENCRYPTION_KEY: ${{secrets.ENCRYPTION_KEY}}
          NONCE: ${{secrets.NONCE}}
        run: |
          heroku container:login
          heroku config:set -a bdb-2021 ENVIRONMENT=${ENVIRONMENT} ENCRYPTION_KEY=${ENCRYPTION_KEY} NONCE=${NONCE}
          heroku container:push web -a bdb-2021
          heroku container:release web -a bdb-2021
